### ISSUE TITLE
Cannot Install from Source Package

### ISSUE THREAD

**Issue by alakae** [resmo/python-cloudscale#18]
Hi

I am currently trying to create a [Homebrew Formula](https://formulae.brew.sh) for `python-cloudscale`. Homebrew uses `pip install --no-binary` under the hood. Unfortunately, there is currently a problem when using this option.

Minimal example to reproduce the error:

```
$ cat <<EOF > Dockerfile
FROM python:3
RUN pip install --no-binary :all: cloudscale
EOF
```
```
$ docker build .
Sending build context to Docker daemon  9.784MB
Step 1/2 : FROM python:3
 ---> efdecc2e377a
Step 2/2 : RUN pip install --no-binary :all: cloudscale
 ---> Running in 13fa634bd3ab
Collecting cloudscale
  Downloading cloudscale-0.10.0.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9bbjx4oi/cloudscale/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9bbjx4oi/cloudscale/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-9bbjx4oi/cloudscale/pip-egg-info
         cwd: /tmp/pip-install-9bbjx4oi/cloudscale/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9bbjx4oi/cloudscale/setup.py", line 10, in <module>
        with open("requirements.txt", "r", encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c pip install --no-binary :all: cloudscale' returned a non-zero code: 1
```

I am definitely not en expert on Python software packaging. However, some quick googling suggests that adding a `MANIFEST.in` that includes the `requirements.txt` might resolve this issue.

Thanks.

**Comment by resmo** [comment]
Fixed by 0.11.1
~~~
Step 1/2 : FROM python:3
 ---> efdecc2e377a
Step 2/2 : RUN pip install --no-binary :all: cloudscale==0.11.1
 ---> Running in 06857b6ce082
Collecting cloudscale==0.11.1
  Downloading cloudscale-0.11.1.tar.gz (20 kB)
Collecting requests
  Downloading requests-2.22.0.tar.gz (113 kB)
Collecting click>=7.0.0
  Downloading Click-7.0.tar.gz (286 kB)
Collecting tabulate
  Downloading tabulate-0.8.6.tar.gz (45 kB)
Collecting pygments
  Downloading Pygments-2.5.2.tar.gz (20.3 MB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4.tar.gz (1.9 MB)
Collecting idna<2.9,>=2.5
  Downloading idna-2.8.tar.gz (174 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading urllib3-1.25.8.tar.gz (261 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2019.11.28.tar.gz (156 kB)
Skipping wheel build for cloudscale, due to binaries being disabled for it.
Skipping wheel build for requests, due to binaries being disabled for it.
Skipping wheel build for click, due to binaries being disabled for it.
Skipping wheel build for tabulate, due to binaries being disabled for it.
Skipping wheel build for pygments, due to binaries being disabled for it.
Skipping wheel build for chardet, due to binaries being disabled for it.
Skipping wheel build for idna, due to binaries being disabled for it.
Skipping wheel build for urllib3, due to binaries being disabled for it.
Skipping wheel build for certifi, due to binaries being disabled for it.
Installing collected packages: chardet, idna, urllib3, certifi, requests, click, tabulate, pygments, cloudscale
    Running setup.py install for chardet: started
    Running setup.py install for chardet: finished with status 'done'
    Running setup.py install for idna: started
    Running setup.py install for idna: finished with status 'done'
    Running setup.py install for urllib3: started
    Running setup.py install for urllib3: finished with status 'done'
    Running setup.py install for certifi: started
    Running setup.py install for certifi: finished with status 'done'
    Running setup.py install for requests: started
    Running setup.py install for requests: finished with status 'done'
    Running setup.py install for click: started
    Running setup.py install for click: finished with status 'done'
    Running setup.py install for tabulate: started
    Running setup.py install for tabulate: finished with status 'done'
    Running setup.py install for pygments: started
    Running setup.py install for pygments: finished with status 'done'
    Running setup.py install for cloudscale: started
    Running setup.py install for cloudscale: finished with status 'done'
Successfully installed certifi-2019.11.28 chardet-3.0.4 click-7.0 cloudscale-0.11.1 idna-2.8 pygments-2.5.2 requests-2.22.0 tabulate-0.8.6 urllib3-1.25.8
 ---> bd4df4ea007a
Removing intermediate container 06857b6ce082
Successfully built bd4df4ea007a
~~~
